# Generated by Django 5.0.4 on 2024-04-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='location',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='manager',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='code',
            field=models.CharField(default='Unknown', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='tt',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='type',
            field=models.CharField(choices=[('S', 'Solidaire'), ('E', 'Economique')], default='Unknown', max_length=1),
            preserve_default=False,
        ),
    ]
